//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardCreator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardCreator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Akvaléir_Normal_v2007 {
            get {
                object obj = ResourceManager.GetObject("Akvaléir_Normal_v2007", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto refresh preview.
        /// </summary>
        public static string AutoRefresh {
            get {
                return ResourceManager.GetString("AutoRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards:.
        /// </summary>
        public static string Cards {
            get {
                return ResourceManager.GetString("Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose file.
        /// </summary>
        public static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose cards.
        /// </summary>
        public static string ChooseImages {
            get {
                return ResourceManager.GetString("ChooseImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choosen cards: .
        /// </summary>
        public static string Choosen {
            get {
                return ResourceManager.GetString("Choosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] colonna_mt {
            get {
                object obj = ResourceManager.GetObject("colonna_mt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To generate cards choose a file with data.
        ///
        ///Generated cards will be saved in dictionary &quot;cards&quot; created in dictionary with choosen file.
        ///Generated pdf file will be saved in dictionary with choosen file with the same name and &quot;pdf&quot; extension.
        ///
        ///To add custom buttons to main window, modify &quot;appsettings.json&quot; file..
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Exocet1 {
            get {
                object obj = ResourceManager.GetObject("Exocet1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Gargoyles_Normal {
            get {
                object obj = ResourceManager.GetObject("Gargoyles_Normal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate cards.
        /// </summary>
        public static string GenerateCards {
            get {
                return ResourceManager.GetString("GenerateCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate images.
        /// </summary>
        public static string GenerateImages {
            get {
                return ResourceManager.GetString("GenerateImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating cards from a template.
        /// </summary>
        public static string GeneratingCards {
            get {
                return ResourceManager.GetString("GeneratingCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating pdf from a template.
        /// </summary>
        public static string GeneratingPdf {
            get {
                return ResourceManager.GetString("GeneratingPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Got_Heroin {
            get {
                object obj = ResourceManager.GetObject("Got_Heroin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical grid.
        /// </summary>
        public static string GridHeight {
            get {
                return ResourceManager.GetString("GridHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal grid.
        /// </summary>
        public static string GridWidth {
            get {
                return ResourceManager.GetString("GridWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome at Card Creator!.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Neverwinter {
            get {
                object obj = ResourceManager.GetObject("Neverwinter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare pdf from choosen files.
        /// </summary>
        public static string PrepareChoosenPdf {
            get {
                return ResourceManager.GetString("PrepareChoosenPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare pdf to print.
        /// </summary>
        public static string PreparePdf {
            get {
                return ResourceManager.GetString("PreparePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a template to show preview..
        /// </summary>
        public static string PreviewHidden {
            get {
                return ResourceManager.GetString("PreviewHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] runic {
            get {
                object obj = ResourceManager.GetObject("runic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] runic_altno {
            get {
                object obj = ResourceManager.GetObject("runic_altno", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save a document as....
        /// </summary>
        public static string SavePdf {
            get {
                return ResourceManager.GetString("SavePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template file:.
        /// </summary>
        public static string SourceFile {
            get {
                return ResourceManager.GetString("SourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] trebuc {
            get {
                object obj = ResourceManager.GetObject("trebuc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] trebucbd {
            get {
                object obj = ResourceManager.GetObject("trebucbd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] trebucbi {
            get {
                object obj = ResourceManager.GetObject("trebucbi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] trebucit {
            get {
                object obj = ResourceManager.GetObject("trebucit", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
