//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardCreator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardCreator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Akvaléir_Normal_v2007 {
            get {
                object obj = ResourceManager.GetObject("Akvaléir_Normal_v2007", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odświeżaj podgląd automatycznie.
        /// </summary>
        public static string AutoRefresh {
            get {
                return ResourceManager.GetString("AutoRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karty:.
        /// </summary>
        public static string Cards {
            get {
                return ResourceManager.GetString("Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz plik.
        /// </summary>
        public static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz karty.
        /// </summary>
        public static string ChooseImages {
            get {
                return ResourceManager.GetString("ChooseImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybrano kart: .
        /// </summary>
        public static string Choosen {
            get {
                return ResourceManager.GetString("Choosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] colonna_mt {
            get {
                object obj = ResourceManager.GetObject("colonna_mt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aby wygenerować karty wskaż plik z danymi.
        ///
        ///Wygenerowane karty zostaną umieszczone w folderze &quot;cards&quot; utworzonym w tym samym katalogu, w którym znajduje się wskazany plik.
        ///Wygenerowany plik pdf zostanie umieszczony w folderze z wybranym plikiem i będzie miał taką samą nazwę.
        ///
        ///Aby dodać nowe przyciski do panelu należy zmodyfikować plik &quot;appsettings.json&quot;..
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Exocet1 {
            get {
                object obj = ResourceManager.GetObject("Exocet1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Gargoyles_Normal {
            get {
                object obj = ResourceManager.GetObject("Gargoyles_Normal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generuj karty.
        /// </summary>
        public static string GenerateCards {
            get {
                return ResourceManager.GetString("GenerateCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generuj obrazki.
        /// </summary>
        public static string GenerateImages {
            get {
                return ResourceManager.GetString("GenerateImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Got_Heroin {
            get {
                object obj = ResourceManager.GetObject("Got_Heroin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siatka pozioma.
        /// </summary>
        public static string GridHeight {
            get {
                return ResourceManager.GetString("GridHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siatka pionowa.
        /// </summary>
        public static string GridWidth {
            get {
                return ResourceManager.GetString("GridWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witaj w kreatorze kart!.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Neverwinter {
            get {
                object obj = ResourceManager.GetObject("Neverwinter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przygotuj pdf z wybranych kart.
        /// </summary>
        public static string PrepareChoosenPdf {
            get {
                return ResourceManager.GetString("PrepareChoosenPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przygotuj pdf do druku.
        /// </summary>
        public static string PreparePdf {
            get {
                return ResourceManager.GetString("PreparePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] runic {
            get {
                object obj = ResourceManager.GetObject("runic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] runic_altno {
            get {
                object obj = ResourceManager.GetObject("runic_altno", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz dokument jako.
        /// </summary>
        public static string SavePdf {
            get {
                return ResourceManager.GetString("SavePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plik z danymi:.
        /// </summary>
        public static string SourceFile {
            get {
                return ResourceManager.GetString("SourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] trebuc {
            get {
                object obj = ResourceManager.GetObject("trebuc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] trebucbd {
            get {
                object obj = ResourceManager.GetObject("trebucbd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] trebucbi {
            get {
                object obj = ResourceManager.GetObject("trebucbi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] trebucit {
            get {
                object obj = ResourceManager.GetObject("trebucit", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
